plugins {
    id 'com.android.application'
}

android {
    namespace 'com.avrahamart.nightscreen'
    compileSdk 36

    defaultConfig {
        applicationId 'com.avrahamart.nightscreen'
        minSdk 26
        targetSdk 36
        versionCode 7
        versionName '1.6'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'com.kosherjava:zmanim:2.5.0'
}
